//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageData", Namespace="http://schemas.datacontract.org/2004/07/CIM.MES.Common.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, object>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, object>>[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.DBNull))]
    public partial class MessageData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMMANDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMMANDTYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, object>> DATADICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object>[] DATALISTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet DATASETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable DATATABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXCEPTIONMESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, object>[] HASHLISTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, object> HASHTABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISREQUESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISSUCCESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LANGUAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object OBJECTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QUERYIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE {
            get {
                return this.CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODEField, value) != true)) {
                    this.CODEField = value;
                    this.RaisePropertyChanged("CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMAND {
            get {
                return this.COMMANDField;
            }
            set {
                if ((object.ReferenceEquals(this.COMMANDField, value) != true)) {
                    this.COMMANDField = value;
                    this.RaisePropertyChanged("COMMAND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMANDTYPE {
            get {
                return this.COMMANDTYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMMANDTYPEField, value) != true)) {
                    this.COMMANDTYPEField = value;
                    this.RaisePropertyChanged("COMMANDTYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, object>> DATADIC {
            get {
                return this.DATADICField;
            }
            set {
                if ((object.ReferenceEquals(this.DATADICField, value) != true)) {
                    this.DATADICField = value;
                    this.RaisePropertyChanged("DATADIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object>[] DATALIST {
            get {
                return this.DATALISTField;
            }
            set {
                if ((object.ReferenceEquals(this.DATALISTField, value) != true)) {
                    this.DATALISTField = value;
                    this.RaisePropertyChanged("DATALIST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet DATASET {
            get {
                return this.DATASETField;
            }
            set {
                if ((object.ReferenceEquals(this.DATASETField, value) != true)) {
                    this.DATASETField = value;
                    this.RaisePropertyChanged("DATASET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable DATATABLE {
            get {
                return this.DATATABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATATABLEField, value) != true)) {
                    this.DATATABLEField = value;
                    this.RaisePropertyChanged("DATATABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXCEPTIONMESSAGE {
            get {
                return this.EXCEPTIONMESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.EXCEPTIONMESSAGEField, value) != true)) {
                    this.EXCEPTIONMESSAGEField = value;
                    this.RaisePropertyChanged("EXCEPTIONMESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, object>[] HASHLIST {
            get {
                return this.HASHLISTField;
            }
            set {
                if ((object.ReferenceEquals(this.HASHLISTField, value) != true)) {
                    this.HASHLISTField = value;
                    this.RaisePropertyChanged("HASHLIST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, object> HASHTABLE {
            get {
                return this.HASHTABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.HASHTABLEField, value) != true)) {
                    this.HASHTABLEField = value;
                    this.RaisePropertyChanged("HASHTABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPADDRESS {
            get {
                return this.IPADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.IPADDRESSField, value) != true)) {
                    this.IPADDRESSField = value;
                    this.RaisePropertyChanged("IPADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISREQUEST {
            get {
                return this.ISREQUESTField;
            }
            set {
                if ((this.ISREQUESTField.Equals(value) != true)) {
                    this.ISREQUESTField = value;
                    this.RaisePropertyChanged("ISREQUEST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISSUCCESS {
            get {
                return this.ISSUCCESSField;
            }
            set {
                if ((this.ISSUCCESSField.Equals(value) != true)) {
                    this.ISSUCCESSField = value;
                    this.RaisePropertyChanged("ISSUCCESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LANGUAGE {
            get {
                return this.LANGUAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.LANGUAGEField, value) != true)) {
                    this.LANGUAGEField = value;
                    this.RaisePropertyChanged("LANGUAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OBJECT {
            get {
                return this.OBJECTField;
            }
            set {
                if ((object.ReferenceEquals(this.OBJECTField, value) != true)) {
                    this.OBJECTField = value;
                    this.RaisePropertyChanged("OBJECT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QUERYID {
            get {
                return this.QUERYIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QUERYIDField, value) != true)) {
                    this.QUERYIDField = value;
                    this.RaisePropertyChanged("QUERYID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITEID {
            get {
                return this.SITEIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SITEIDField, value) != true)) {
                    this.SITEIDField = value;
                    this.RaisePropertyChanged("SITEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TID {
            get {
                return this.TIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TIDField, value) != true)) {
                    this.TIDField = value;
                    this.RaisePropertyChanged("TID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERID {
            get {
                return this.USERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.USERIDField, value) != true)) {
                    this.USERIDField = value;
                    this.RaisePropertyChanged("USERID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMesRuleService")]
    public interface IMesRuleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesRuleService/ExecCommand", ReplyAction="http://tempuri.org/IMesRuleService/ExecCommandResponse")]
        WpfApp1.ServiceReference1.MessageData ExecCommand(WpfApp1.ServiceReference1.MessageData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesRuleService/ExecCommand", ReplyAction="http://tempuri.org/IMesRuleService/ExecCommandResponse")]
        System.Threading.Tasks.Task<WpfApp1.ServiceReference1.MessageData> ExecCommandAsync(WpfApp1.ServiceReference1.MessageData requestData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesRuleServiceChannel : WpfApp1.ServiceReference1.IMesRuleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesRuleServiceClient : System.ServiceModel.ClientBase<WpfApp1.ServiceReference1.IMesRuleService>, WpfApp1.ServiceReference1.IMesRuleService {
        
        public MesRuleServiceClient() {
        }
        
        public MesRuleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MesRuleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesRuleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesRuleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfApp1.ServiceReference1.MessageData ExecCommand(WpfApp1.ServiceReference1.MessageData requestData) {
            return base.Channel.ExecCommand(requestData);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.ServiceReference1.MessageData> ExecCommandAsync(WpfApp1.ServiceReference1.MessageData requestData) {
            return base.Channel.ExecCommandAsync(requestData);
        }
    }
}
