//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bh_test.BHDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteInfo", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager.MsSql.Data")]
    [System.SerializableAttribute()]
    public partial class ExecuteInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.CallerInfo CallerInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.CommandType CommandTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ConnectionType ConnectionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.CustomDatabaseInfo DatabaseInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.DataBaseType ExecuteDBTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecuteQueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ExecuteService ExecuteServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ExecuteType ExecuteTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.BatchInfo[] LstBatchInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.MsSqlParameter[] ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoredProcedureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.XNTransactionScope XNTransactionScopeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.CallerInfo CallerInfo {
            get {
                return this.CallerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerInfoField, value) != true)) {
                    this.CallerInfoField = value;
                    this.RaisePropertyChanged("CallerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.CommandType CommandType {
            get {
                return this.CommandTypeField;
            }
            set {
                if ((this.CommandTypeField.Equals(value) != true)) {
                    this.CommandTypeField = value;
                    this.RaisePropertyChanged("CommandType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ConnectionType ConnectionType {
            get {
                return this.ConnectionTypeField;
            }
            set {
                if ((this.ConnectionTypeField.Equals(value) != true)) {
                    this.ConnectionTypeField = value;
                    this.RaisePropertyChanged("ConnectionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.CustomDatabaseInfo DatabaseInfo {
            get {
                return this.DatabaseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseInfoField, value) != true)) {
                    this.DatabaseInfoField = value;
                    this.RaisePropertyChanged("DatabaseInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.DataBaseType ExecuteDBType {
            get {
                return this.ExecuteDBTypeField;
            }
            set {
                if ((this.ExecuteDBTypeField.Equals(value) != true)) {
                    this.ExecuteDBTypeField = value;
                    this.RaisePropertyChanged("ExecuteDBType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecuteQuery {
            get {
                return this.ExecuteQueryField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecuteQueryField, value) != true)) {
                    this.ExecuteQueryField = value;
                    this.RaisePropertyChanged("ExecuteQuery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ExecuteService ExecuteService {
            get {
                return this.ExecuteServiceField;
            }
            set {
                if ((this.ExecuteServiceField.Equals(value) != true)) {
                    this.ExecuteServiceField = value;
                    this.RaisePropertyChanged("ExecuteService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ExecuteType ExecuteType {
            get {
                return this.ExecuteTypeField;
            }
            set {
                if ((this.ExecuteTypeField.Equals(value) != true)) {
                    this.ExecuteTypeField = value;
                    this.RaisePropertyChanged("ExecuteType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GMT {
            get {
                return this.GMTField;
            }
            set {
                if ((this.GMTField.Equals(value) != true)) {
                    this.GMTField = value;
                    this.RaisePropertyChanged("GMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.BatchInfo[] LstBatchInfo {
            get {
                return this.LstBatchInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LstBatchInfoField, value) != true)) {
                    this.LstBatchInfoField = value;
                    this.RaisePropertyChanged("LstBatchInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.MsSqlParameter[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoredProcedureName {
            get {
                return this.StoredProcedureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StoredProcedureNameField, value) != true)) {
                    this.StoredProcedureNameField = value;
                    this.RaisePropertyChanged("StoredProcedureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.XNTransactionScope XNTransactionScope {
            get {
                return this.XNTransactionScopeField;
            }
            set {
                if ((this.XNTransactionScopeField.Equals(value) != true)) {
                    this.XNTransactionScopeField = value;
                    this.RaisePropertyChanged("XNTransactionScope");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallerInfo", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager.MsSql.Data")]
    [System.SerializableAttribute()]
    public partial class CallerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Plant_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Screen_PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Session_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGroup_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plant_Code {
            get {
                return this.Plant_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Plant_CodeField, value) != true)) {
                    this.Plant_CodeField = value;
                    this.RaisePropertyChanged("Plant_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Screen_Path {
            get {
                return this.Screen_PathField;
            }
            set {
                if ((object.ReferenceEquals(this.Screen_PathField, value) != true)) {
                    this.Screen_PathField = value;
                    this.RaisePropertyChanged("Screen_Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Session_ID {
            get {
                return this.Session_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Session_IDField, value) != true)) {
                    this.Session_IDField = value;
                    this.RaisePropertyChanged("Session_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGroup_Code {
            get {
                return this.UserGroup_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGroup_CodeField, value) != true)) {
                    this.UserGroup_CodeField = value;
                    this.RaisePropertyChanged("UserGroup_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.User_IDField, value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomDatabaseInfo", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager.MsSql.Data")]
    [System.SerializableAttribute()]
    public partial class CustomDatabaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsSqlDatabaseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsSqlServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsSqlUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsSqlUserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsSqlDatabaseName {
            get {
                return this.MsSqlDatabaseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MsSqlDatabaseNameField, value) != true)) {
                    this.MsSqlDatabaseNameField = value;
                    this.RaisePropertyChanged("MsSqlDatabaseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsSqlServer {
            get {
                return this.MsSqlServerField;
            }
            set {
                if ((object.ReferenceEquals(this.MsSqlServerField, value) != true)) {
                    this.MsSqlServerField = value;
                    this.RaisePropertyChanged("MsSqlServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsSqlUserID {
            get {
                return this.MsSqlUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MsSqlUserIDField, value) != true)) {
                    this.MsSqlUserIDField = value;
                    this.RaisePropertyChanged("MsSqlUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsSqlUserPassword {
            get {
                return this.MsSqlUserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MsSqlUserPasswordField, value) != true)) {
                    this.MsSqlUserPasswordField = value;
                    this.RaisePropertyChanged("MsSqlUserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandType", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum CommandType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StoredProcedure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchExecute = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderDetail = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderDetailList = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionType", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum ConnectionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataBaseType", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum DataBaseType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MsSql = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Oracle = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DB2 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteService", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum ExecuteService : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoneTransaction = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transaction = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteType", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum ExecuteType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Return = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonReturn = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchInfo", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager.MsSql.Data")]
    [System.SerializableAttribute()]
    public partial class BatchInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.CommandType CommandTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ConnectionType ConnectionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.CustomDatabaseInfo DatabaseInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.BatchInfo[] DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.DataBaseType ExecuteDBTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecuteQueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ExecuteService ExecuteServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ExecuteType ExecuteTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.MsSqlParameter[] ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoredProcedureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.XNTransactionScope XNTransactionScopeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.CommandType CommandType {
            get {
                return this.CommandTypeField;
            }
            set {
                if ((this.CommandTypeField.Equals(value) != true)) {
                    this.CommandTypeField = value;
                    this.RaisePropertyChanged("CommandType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ConnectionType ConnectionType {
            get {
                return this.ConnectionTypeField;
            }
            set {
                if ((this.ConnectionTypeField.Equals(value) != true)) {
                    this.ConnectionTypeField = value;
                    this.RaisePropertyChanged("ConnectionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.CustomDatabaseInfo DatabaseInfo {
            get {
                return this.DatabaseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseInfoField, value) != true)) {
                    this.DatabaseInfoField = value;
                    this.RaisePropertyChanged("DatabaseInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.BatchInfo[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.DataBaseType ExecuteDBType {
            get {
                return this.ExecuteDBTypeField;
            }
            set {
                if ((this.ExecuteDBTypeField.Equals(value) != true)) {
                    this.ExecuteDBTypeField = value;
                    this.RaisePropertyChanged("ExecuteDBType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecuteQuery {
            get {
                return this.ExecuteQueryField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecuteQueryField, value) != true)) {
                    this.ExecuteQueryField = value;
                    this.RaisePropertyChanged("ExecuteQuery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ExecuteService ExecuteService {
            get {
                return this.ExecuteServiceField;
            }
            set {
                if ((this.ExecuteServiceField.Equals(value) != true)) {
                    this.ExecuteServiceField = value;
                    this.RaisePropertyChanged("ExecuteService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ExecuteType ExecuteType {
            get {
                return this.ExecuteTypeField;
            }
            set {
                if ((this.ExecuteTypeField.Equals(value) != true)) {
                    this.ExecuteTypeField = value;
                    this.RaisePropertyChanged("ExecuteType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GMT {
            get {
                return this.GMTField;
            }
            set {
                if ((this.GMTField.Equals(value) != true)) {
                    this.GMTField = value;
                    this.RaisePropertyChanged("GMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.MsSqlParameter[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoredProcedureName {
            get {
                return this.StoredProcedureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StoredProcedureNameField, value) != true)) {
                    this.StoredProcedureNameField = value;
                    this.RaisePropertyChanged("StoredProcedureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.XNTransactionScope XNTransactionScope {
            get {
                return this.XNTransactionScopeField;
            }
            set {
                if ((this.XNTransactionScopeField.Equals(value) != true)) {
                    this.XNTransactionScopeField = value;
                    this.RaisePropertyChanged("XNTransactionScope");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsSqlParameter", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager.MsSql.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.DBNull))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ExecuteInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.CallerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.CustomDatabaseInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.BatchInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.BatchInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.MsSqlParameter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ExecuteResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ReturnValueItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ReturnValueItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.CommandType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ConnectionType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.DataBaseType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ExecuteService))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ExecuteType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.AutoRollback))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ParamDirection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ParameterType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.DatabaseReturnType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.XNTransactionScope))]
    public partial class MsSqlParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.AutoRollback AutoRollbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ParamDirection DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ParameterType ParameterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.DatabaseReturnType ReturnValueTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToParameterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.AutoRollback AutoRollback {
            get {
                return this.AutoRollbackField;
            }
            set {
                if ((this.AutoRollbackField.Equals(value) != true)) {
                    this.AutoRollbackField = value;
                    this.RaisePropertyChanged("AutoRollback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ParamDirection Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsString {
            get {
                return this.IsStringField;
            }
            set {
                if ((this.IsStringField.Equals(value) != true)) {
                    this.IsStringField = value;
                    this.RaisePropertyChanged("IsString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ParameterType ParameterType {
            get {
                return this.ParameterTypeField;
            }
            set {
                if ((this.ParameterTypeField.Equals(value) != true)) {
                    this.ParameterTypeField = value;
                    this.RaisePropertyChanged("ParameterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.DatabaseReturnType ReturnValueType {
            get {
                return this.ReturnValueTypeField;
            }
            set {
                if ((this.ReturnValueTypeField.Equals(value) != true)) {
                    this.ReturnValueTypeField = value;
                    this.RaisePropertyChanged("ReturnValueType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToParameterName {
            get {
                return this.ToParameterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToParameterNameField, value) != true)) {
                    this.ToParameterNameField = value;
                    this.RaisePropertyChanged("ToParameterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XNTransactionScope", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum XNTransactionScope : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Start = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proceed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        End = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteResult", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager.MsSql.Data")]
    [System.SerializableAttribute()]
    public partial class ExecuteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExecuteSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet ResultDataSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ReturnValueItem[] ResultVariableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExecuteSuccess {
            get {
                return this.ExecuteSuccessField;
            }
            set {
                if ((this.ExecuteSuccessField.Equals(value) != true)) {
                    this.ExecuteSuccessField = value;
                    this.RaisePropertyChanged("ExecuteSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet ResultDataSet {
            get {
                return this.ResultDataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDataSetField, value) != true)) {
                    this.ResultDataSetField = value;
                    this.RaisePropertyChanged("ResultDataSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ReturnValueItem[] ResultVariable {
            get {
                return this.ResultVariableField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultVariableField, value) != true)) {
                    this.ResultVariableField = value;
                    this.RaisePropertyChanged("ResultVariable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnValueItem", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager.MsSql.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.DBNull))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ExecuteInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.CallerInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.CustomDatabaseInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.BatchInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.BatchInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.MsSqlParameter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.MsSqlParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ExecuteResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ReturnValueItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.CommandType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ConnectionType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.DataBaseType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ExecuteService))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ExecuteType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.AutoRollback))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ParamDirection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.ParameterType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.DatabaseReturnType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(bh_test.BHDataService.XNTransactionScope))]
    public partial class ReturnValueItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bh_test.BHDataService.ParameterType ParameterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToParameterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bh_test.BHDataService.ParameterType ParameterType {
            get {
                return this.ParameterTypeField;
            }
            set {
                if ((this.ParameterTypeField.Equals(value) != true)) {
                    this.ParameterTypeField = value;
                    this.RaisePropertyChanged("ParameterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToParameterName {
            get {
                return this.ToParameterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToParameterNameField, value) != true)) {
                    this.ToParameterNameField = value;
                    this.RaisePropertyChanged("ToParameterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoRollback", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum AutoRollback : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rollback = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamDirection", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum ParamDirection : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Input = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Output = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InputOutput = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnValue = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterType", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum ParameterType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DetailParam = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseReturnType", Namespace="http://schemas.datacontract.org/2004/07/XN.Manager")]
    public enum DatabaseReturnType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cursor = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Value = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BHDataService.XNDataManagerService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface XNDataManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XNDataManagerService/ExecuteQuery", ReplyAction="http://tempuri.org/XNDataManagerService/ExecuteQueryResponse")]
        bh_test.BHDataService.ExecuteResult ExecuteQuery(bh_test.BHDataService.ExecuteInfo exInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XNDataManagerService/ExecuteQuery", ReplyAction="http://tempuri.org/XNDataManagerService/ExecuteQueryResponse")]
        System.Threading.Tasks.Task<bh_test.BHDataService.ExecuteResult> ExecuteQueryAsync(bh_test.BHDataService.ExecuteInfo exInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XNDataManagerServiceChannel : bh_test.BHDataService.XNDataManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XNDataManagerServiceClient : System.ServiceModel.ClientBase<bh_test.BHDataService.XNDataManagerService>, bh_test.BHDataService.XNDataManagerService {
        
        public XNDataManagerServiceClient() {
        }
        
        public XNDataManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XNDataManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XNDataManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XNDataManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bh_test.BHDataService.ExecuteResult ExecuteQuery(bh_test.BHDataService.ExecuteInfo exInfo) {
            return base.Channel.ExecuteQuery(exInfo);
        }
        
        public System.Threading.Tasks.Task<bh_test.BHDataService.ExecuteResult> ExecuteQueryAsync(bh_test.BHDataService.ExecuteInfo exInfo) {
            return base.Channel.ExecuteQueryAsync(exInfo);
        }
    }
}
