CREATE TABLE [dbo].[Sheet1$] (
    [input_time]          DATETIME       NULL,
    [modfied_time]        DATETIME       NULL,
    [completed_time]      DATETIME       NULL,
    [customer_code]       NVARCHAR (255) NULL,
    [customer_name]       NVARCHAR (255) NULL,
    [input_username]      NVARCHAR (255) NULL,
    [lastmodify_username] NVARCHAR (255) NULL,
    [complete_username]   NVARCHAR (255) NULL,
    [lotid]               NVARCHAR (255) NULL,
    [order_type]          NVARCHAR (255) NULL,
    [pnlqty]              FLOAT (53)     NULL,
    [lotinfo_mesprcname]  NVARCHAR (255) NULL,
    [lotinfo_mesprcid]    FLOAT (53)     NULL,
    [lotinfo_customer]    NVARCHAR (255) NULL,
    [lotinfo_layer]       NVARCHAR (255) NULL,
    [lotinfo_prctype]     NVARCHAR (255) NULL,
    [lotinfo_toolno]      NVARCHAR (255) NULL,
    [lotinfo_modelname]   NVARCHAR (255) NULL,
    [lotinfo_rev]         NVARCHAR (255) NULL,
    [lotinfo_pnlpcsqty]   FLOAT (53)     NULL,
    [lotinfo_worksizex]   FLOAT (53)     NULL,
    [lotinfo_worksizey]   FLOAT (53)     NULL,
    [lotinfo_holecount]   FLOAT (53)     NULL,
    [note]                NVARCHAR (255) NULL,
    [machine_cs]          FLOAT (53)     NULL,
    [machine_ss]          NVARCHAR (255) NULL,
    [isDone]              NVARCHAR (255) NULL,
    [isPrinted]           NVARCHAR (255) NULL
);

