CREATE TABLE [dbo].[tb_uv_toolinfo] (
    [product_id]      NVARCHAR (100) NOT NULL,
    [cust_toolno]     NVARCHAR (100) NOT NULL,
    [cust_modelname]  NVARCHAR (200) NULL,
    [create_date]     DATETIME       NULL,
    [cust_id]         NVARCHAR (10)  NULL,
    [sample]          BIT            NULL,
    [worksize_x]      DECIMAL (6, 2) NULL,
    [worksize_y]      DECIMAL (6, 2) NULL,
    [array_blk]       INT            NULL,
    [pcs]             INT            NULL,
    [layer]           INT            NULL,
    [mes_prc_code]    NVARCHAR (10)  NULL,
    [mes_prc_name]    NVARCHAR (30)  NULL,
    [end_customer]    NVARCHAR (100) NULL,
    [product_type]    NVARCHAR (20)  NULL,
    [prc_code]        NVARCHAR (20)  NULL,
    [cust_revision]   NCHAR (10)     NULL,
    [tool_notes]      NTEXT          NULL,
    [cust_comment]    NTEXT          NULL,
    [depth]           DECIMAL (7, 3) NULL,
    [insul_type]      NVARCHAR (30)  NULL,
    [hole_count]      NVARCHAR (50)  NULL,
    [main_hole_size]  NVARCHAR (10)  NULL,
    [mes_seq_code]    NVARCHAR (10)  NULL,
    [PrcLayerFrom_1]  NVARCHAR (4)   NULL,
    [PrcLayerTo_1]    NVARCHAR (4)   NULL,
    [StackType]       NVARCHAR (20)  NULL,
    [PrdCategory]     NVARCHAR (200) NULL,
    [LayerStructure]  NVARCHAR (10)  NULL,
    [customer_shipto] NVARCHAR (200) NULL,
    [PrcLayerFrom_2]  NVARCHAR (4)   NULL,
    [PrcLayerTo_2]    NVARCHAR (4)   NULL,
    [hole_count_1]    NCHAR (10)     NULL,
    [hole_count_2]    NCHAR (10)     NULL,
    [hole_count_pth]  NCHAR (10)     NULL,
    [cust_name]       NVARCHAR (30)  NULL,
    [prc_name]        NVARCHAR (20)  NULL,
    [insul_info]      NTEXT          NULL,
    [insul_thickness] DECIMAL (7, 3) NULL,
    [cu_thickness]    DECIMAL (7, 3) NULL,
    [pcsperstrip]     INT            NULL,
    [pcssize_x]       DECIMAL (6, 2) NULL,
    [pcssize_y]       DECIMAL (6, 2) NULL,
    [striparrayCol]   INT            NULL,
    [striparrayRow]   INT            NULL,
    [striparrayBlk]   INT            NULL,
    CONSTRAINT [PK_tb_toolinfo] PRIMARY KEY CLUSTERED ([product_id] ASC),
    CONSTRAINT [tb_toolinfo_FK_custid] FOREIGN KEY ([cust_id]) REFERENCES [dbo].[tb_customer] ([cust_id]),
    CONSTRAINT [tb_toolinfo_FK_prccode] FOREIGN KEY ([prc_code]) REFERENCES [dbo].[tb_prctype] ([prc_code])
);


GO
CREATE NONCLUSTERED INDEX [IX_tb_toolinfo]
    ON [dbo].[tb_uv_toolinfo]([product_type] ASC, [prc_code] ASC, [cust_toolno] ASC) WITH (FILLFACTOR = 100);

