// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DAWON_UV_INVENTORY_PROTO.Models
{
    public partial class Db_Uv_InventoryContext : DbContext
    {
        public Db_Uv_InventoryContext()
        {
        }

        public Db_Uv_InventoryContext(DbContextOptions<Db_Uv_InventoryContext> options)
            : base(options)
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured && MainWindow._mainwindowViewModel.SelectedUser == "테스트" && MainWindow._mainwindowViewModel.ChkTest == true)
            {
                //optionsBuilder.UseNpgsql("Host=192.168.0.21;Database=uv_inventory;Username=uv_inventory;Password=Ekdnjs3637!");
                optionsBuilder.UseSqlServer("server=192.168.0.12;database=db_uv_inventory;user=uv_inventory;password=Ekdnjs3637!");
                optionsBuilder.UseModel(Db_Uv_InventoryContextModel.Instance);

            }
            else if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("server=192.168.0.3;database=db_uv_inventory;user=uv_inventory;password=Ekdnjs3637!");
                optionsBuilder.UseModel(Db_Uv_InventoryContextModel.Instance);
            }
        }
        public virtual DbSet<TbBomYpeMaterial> TbBomYpeMaterial { get; set; }
        public virtual DbSet<TbCustomer> TbCustomer { get; set; }
        public virtual DbSet<TbMachine> TbMachine { get; set; }
        public virtual DbSet<TbPrctype> TbPrctype { get; set; }
        public virtual DbSet<TbUsers> TbUsers { get; set; }
        public virtual DbSet<TbUvToolinfo> TbUvToolinfo { get; set; }
        public virtual DbSet<TbUvWorkorder> TbUvWorkorder { get; set; }
        public virtual DbSet<ViewUvWorkorder> ViewUvWorkorder { get; set; }
        public virtual DbSet<ViewUvWorkorder2> ViewUvWorkorder2 { get; set; }
        public virtual DbSet<ViewUvWorkorderDone> ViewUvWorkorderDone { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TbBomYpeMaterial>(entity =>
            {
                entity.HasKey(e => e.Bomid);

                entity.ToTable("tb_bom_ype_material");

                entity.Property(e => e.Bomid)
                    .HasMaxLength(100)
                    .HasColumnName("bomid");

                entity.Property(e => e.Arraypcs).HasColumnName("arraypcs");

                entity.Property(e => e.Assemblyitembomid)
                    .HasMaxLength(100)
                    .HasColumnName("assemblyitembomid");

                entity.Property(e => e.Assemblyitemid)
                    .HasMaxLength(100)
                    .HasColumnName("assemblyitemid");

                entity.Property(e => e.Assemblyitemversion)
                    .HasMaxLength(100)
                    .HasColumnName("assemblyitemversion");

                entity.Property(e => e.Assemblyqty).HasColumnName("assemblyqty");

                entity.Property(e => e.Botassemblyitemname)
                    .HasMaxLength(200)
                    .HasColumnName("botassemblyitemname");

                entity.Property(e => e.Calculatepcs)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("calculatepcs");

                entity.Property(e => e.Color)
                    .HasMaxLength(100)
                    .HasColumnName("color");

                entity.Property(e => e.Consumabletype)
                    .HasMaxLength(100)
                    .HasColumnName("consumabletype");

                entity.Property(e => e.Consumabletype2)
                    .HasMaxLength(300)
                    .HasColumnName("consumabletype2");

                entity.Property(e => e.Inktype)
                    .HasMaxLength(300)
                    .HasColumnName("inktype");

                entity.Property(e => e.Lvl).HasColumnName("lvl");

                entity.Property(e => e.Maker)
                    .HasMaxLength(100)
                    .HasColumnName("maker");

                entity.Property(e => e.Parentbomid)
                    .HasColumnType("ntext")
                    .HasColumnName("parentbomid");

                entity.Property(e => e.ParentsAssemblyitemid)
                    .HasColumnType("ntext")
                    .HasColumnName("parents_assemblyitemid");

                entity.Property(e => e.ParentsAssemblyitemversion)
                    .HasColumnType("ntext")
                    .HasColumnName("parents_assemblyitemversion");

                entity.Property(e => e.Plantid)
                    .HasMaxLength(100)
                    .HasColumnName("plantid");

                entity.Property(e => e.Pnlsize)
                    .HasColumnType("ntext")
                    .HasColumnName("pnlsize");

                entity.Property(e => e.Pnlsizexaxis).HasColumnName("pnlsizexaxis");

                entity.Property(e => e.Pnlsizeyaxis).HasColumnName("pnlsizeyaxis");

                entity.Property(e => e.Requirementqty).HasColumnName("requirementqty");

                entity.Property(e => e.RootAssemblyitemid)
                    .HasMaxLength(100)
                    .HasColumnName("root_assemblyitemid");

                entity.Property(e => e.RootAssemblyitemversion)
                    .HasMaxLength(100)
                    .HasColumnName("root_assemblyitemversion");

                entity.Property(e => e.RootBomid)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("root_bomid");

                entity.Property(e => e.Spec)
                    .HasMaxLength(100)
                    .HasColumnName("spec");

                entity.Property(e => e.Userlayer)
                    .HasMaxLength(300)
                    .HasColumnName("userlayer");

                entity.Property(e => e.Usersequence)
                    .HasColumnType("ntext")
                    .HasColumnName("usersequence");

                entity.Property(e => e.Workmethod)
                    .HasMaxLength(200)
                    .HasColumnName("workmethod");

                entity.Property(e => e.Worksurface)
                    .HasColumnType("ntext")
                    .HasColumnName("worksurface");
            });

            modelBuilder.Entity<TbCustomer>(entity =>
            {
                entity.HasKey(e => e.CustId);

                entity.ToTable("tb_customer");

                entity.HasIndex(e => e.CustCode, "UNIQUE_customer_code")
                    .IsUnique();

                entity.Property(e => e.CustId)
                    .HasMaxLength(10)
                    .HasColumnName("cust_id");

                entity.Property(e => e.CustCode)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("cust_code")
                    .IsFixedLength();

                entity.Property(e => e.CustName)
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnName("cust_name");
            });

            modelBuilder.Entity<TbMachine>(entity =>
            {
                entity.HasKey(e => e.MachineId)
                    .HasName("tb_machine_PK");

                entity.ToTable("tb_machine");

                entity.Property(e => e.MachineId)
                    .HasMaxLength(10)
                    .HasColumnName("machine_id");

                entity.Property(e => e.Department)
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnName("department");

                entity.Property(e => e.MachineMaker)
                    .HasMaxLength(50)
                    .HasColumnName("machine_maker");

                entity.Property(e => e.MachineModelname)
                    .HasMaxLength(50)
                    .HasColumnName("machine_modelname");

                entity.Property(e => e.MachineName)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("machine_name");

                entity.Property(e => e.MachineShortname)
                    .HasMaxLength(3)
                    .HasColumnName("machine_shortname");
            });

            modelBuilder.Entity<TbPrctype>(entity =>
            {
                entity.HasKey(e => e.PrcCode);

                entity.ToTable("tb_prctype");

                entity.Property(e => e.PrcCode)
                    .HasMaxLength(20)
                    .HasColumnName("prc_code");

                entity.Property(e => e.PrcName)
                    .HasMaxLength(20)
                    .HasColumnName("prc_name");
            });

            modelBuilder.Entity<TbUsers>(entity =>
            {
                entity.HasKey(e => e.UserId);

                entity.ToTable("tb_users");

                entity.HasIndex(e => e.UserId, "UNIQUE_user_id")
                    .IsUnique();

                entity.Property(e => e.UserId)
                    .HasMaxLength(20)
                    .HasColumnName("user_id");

                entity.Property(e => e.IsRetired)
                    .HasColumnName("isRetired")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.UserGroup)
                    .HasMaxLength(20)
                    .HasColumnName("user_group");

                entity.Property(e => e.UserName)
                    .HasMaxLength(20)
                    .HasColumnName("user_name");

                entity.Property(e => e.UserRole)
                    .HasMaxLength(20)
                    .HasColumnName("user_role");
            });

            modelBuilder.Entity<TbUvToolinfo>(entity =>
            {
                entity.HasKey(e => e.ProductId)
                    .HasName("PK_tb_toolinfo");

                entity.ToTable("tb_uv_toolinfo");

                entity.HasIndex(e => new { e.ProductType, e.PrcCode, e.CustToolno }, "IX_tb_toolinfo")
                    .HasFillFactor(100);

                entity.Property(e => e.ProductId)
                    .HasMaxLength(100)
                    .HasColumnName("product_id");

                entity.Property(e => e.ArrayBlk).HasColumnName("array_blk");

                entity.Property(e => e.CamFinished).HasDefaultValueSql("((0))");

                entity.Property(e => e.CreateDate)
                    .HasMaxLength(20)
                    .HasColumnName("create_date");

                entity.Property(e => e.CuThickness)
                    .HasColumnType("decimal(7, 3)")
                    .HasColumnName("cu_thickness");

                entity.Property(e => e.CustComment)
                    .HasColumnType("ntext")
                    .HasColumnName("cust_comment");

                entity.Property(e => e.CustId)
                    .HasMaxLength(10)
                    .HasColumnName("cust_id");

                entity.Property(e => e.CustModelname)
                    .HasMaxLength(200)
                    .HasColumnName("cust_modelname");

                entity.Property(e => e.CustName)
                    .HasMaxLength(30)
                    .HasColumnName("cust_name");

                entity.Property(e => e.CustRevision)
                    .HasMaxLength(20)
                    .HasColumnName("cust_revision");

                entity.Property(e => e.CustToolno)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("cust_toolno");

                entity.Property(e => e.CustomerShipto)
                    .HasMaxLength(200)
                    .HasColumnName("customer_shipto");

                entity.Property(e => e.Depth)
                    .HasColumnType("decimal(7, 3)")
                    .HasColumnName("depth");

                entity.Property(e => e.EndCustomer)
                    .HasMaxLength(100)
                    .HasColumnName("end_customer");

                entity.Property(e => e.HoleCount)
                    .HasMaxLength(50)
                    .HasColumnName("hole_count");

                entity.Property(e => e.HoleCount1)
                    .HasMaxLength(10)
                    .HasColumnName("hole_count_1")
                    .IsFixedLength();

                entity.Property(e => e.HoleCount2)
                    .HasMaxLength(10)
                    .HasColumnName("hole_count_2")
                    .IsFixedLength();

                entity.Property(e => e.HoleCountPth)
                    .HasMaxLength(10)
                    .HasColumnName("hole_count_pth")
                    .IsFixedLength();

                entity.Property(e => e.InsulInfo)
                    .HasColumnType("ntext")
                    .HasColumnName("insul_info");

                entity.Property(e => e.InsulThickness)
                    .HasColumnType("decimal(7, 3)")
                    .HasColumnName("insul_thickness");

                entity.Property(e => e.InsulType)
                    .HasMaxLength(30)
                    .HasColumnName("insul_type");

                entity.Property(e => e.Layer).HasColumnName("layer");

                entity.Property(e => e.LayerStructure).HasMaxLength(10);

                entity.Property(e => e.MainHoleSize)
                    .HasMaxLength(10)
                    .HasColumnName("main_hole_size");

                entity.Property(e => e.MesPrcCode)
                    .HasMaxLength(100)
                    .HasColumnName("mes_prc_code");

                entity.Property(e => e.MesPrcName)
                    .HasMaxLength(200)
                    .HasColumnName("mes_prc_name");

                entity.Property(e => e.MesSeqCode)
                    .HasMaxLength(10)
                    .HasColumnName("mes_seq_code");

                entity.Property(e => e.Pcs).HasColumnName("pcs");

                entity.Property(e => e.Pcsperstrip).HasColumnName("pcsperstrip");

                entity.Property(e => e.PcssizeX)
                    .HasColumnType("decimal(6, 2)")
                    .HasColumnName("pcssize_x");

                entity.Property(e => e.PcssizeY)
                    .HasColumnType("decimal(6, 2)")
                    .HasColumnName("pcssize_y");

                entity.Property(e => e.PrcCode)
                    .HasMaxLength(20)
                    .HasColumnName("prc_code");

                entity.Property(e => e.PrcLayerFrom1)
                    .HasMaxLength(10)
                    .HasColumnName("PrcLayerFrom_1");

                entity.Property(e => e.PrcLayerFrom2)
                    .HasMaxLength(10)
                    .HasColumnName("PrcLayerFrom_2");

                entity.Property(e => e.PrcLayerTo1)
                    .HasMaxLength(10)
                    .HasColumnName("PrcLayerTo_1");

                entity.Property(e => e.PrcLayerTo2)
                    .HasMaxLength(10)
                    .HasColumnName("PrcLayerTo_2");

                entity.Property(e => e.PrcName)
                    .HasMaxLength(20)
                    .HasColumnName("prc_name");

                entity.Property(e => e.PrdCategory).HasMaxLength(200);

                entity.Property(e => e.ProductType)
                    .HasMaxLength(20)
                    .HasColumnName("product_type");

                entity.Property(e => e.Sample).HasColumnName("sample");

                entity.Property(e => e.SemCsdata)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("sem_csdata");

                entity.Property(e => e.SemSsdata)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("sem_ssdata");

                entity.Property(e => e.StackType).HasMaxLength(20);

                entity.Property(e => e.StriparrayBlk).HasColumnName("striparrayBlk");

                entity.Property(e => e.StriparrayCol).HasColumnName("striparrayCol");

                entity.Property(e => e.StriparrayRow).HasColumnName("striparrayRow");

                entity.Property(e => e.ToolNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("tool_notes");

                entity.Property(e => e.WorksizeX)
                    .HasColumnType("decimal(6, 2)")
                    .HasColumnName("worksize_x");

                entity.Property(e => e.WorksizeY)
                    .HasColumnType("decimal(6, 2)")
                    .HasColumnName("worksize_y");

                entity.Property(e => e.YpNextResourceDefault)
                    .HasMaxLength(200)
                    .HasColumnName("yp_next_resource_default");

                entity.Property(e => e.YpNextResourcelist)
                    .HasColumnType("ntext")
                    .HasColumnName("yp_next_resourcelist");

                entity.Property(e => e.YpeDatarev)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("ype_datarev");

                entity.HasOne(d => d.Cust)
                    .WithMany(p => p.TbUvToolinfo)
                    .HasForeignKey(d => d.CustId)
                    .HasConstraintName("tb_toolinfo_FK_custid");

                entity.HasOne(d => d.PrcCodeNavigation)
                    .WithMany(p => p.TbUvToolinfo)
                    .HasForeignKey(d => d.PrcCode)
                    .HasConstraintName("tb_toolinfo_FK_prccode");
            });

            modelBuilder.Entity<TbUvWorkorder>(entity =>
            {
                entity.ToTable("tb_uv_workorder");

                entity.HasIndex(e => new { e.TrackoutTime, e.CustId, e.IsDone }, "IX_tb_uv_workorder");

                entity.HasIndex(e => new { e.IsDone, e.Id, e.TrackoutUserId, e.TrackinUserId, e.ProductId }, "_dta_index_tb_uv_workorder_5_805577908__K15_K18_K7_K6_K11_2_3_4_5_8_9_10_13_14_16_19_20_21_22_23");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("create_time");

                entity.Property(e => e.CustId)
                    .HasMaxLength(10)
                    .HasColumnName("cust_id");

                entity.Property(e => e.FormatBg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Format_bg");

                entity.Property(e => e.FormatBold).HasColumnName("Format_bold");

                entity.Property(e => e.FormatFg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Format_fg");

                entity.Property(e => e.IsDone)
                    .HasColumnName("isDone")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.IsPrinted)
                    .HasColumnName("isPrinted")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.LotHistory).HasColumnType("ntext");

                entity.Property(e => e.LotNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("lot_notes");

                entity.Property(e => e.LotType)
                    .HasMaxLength(20)
                    .HasColumnName("lot_type");

                entity.Property(e => e.Lotid)
                    .HasMaxLength(100)
                    .HasColumnName("lotid");

                entity.Property(e => e.MachineCs)
                    .HasMaxLength(300)
                    .HasColumnName("machine_cs");

                entity.Property(e => e.MachineSs)
                    .HasMaxLength(300)
                    .HasColumnName("machine_ss");

                entity.Property(e => e.NftOrderserial)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("nft_orderserial");

                entity.Property(e => e.Pnlqty).HasColumnName("pnlqty");

                entity.Property(e => e.ProductId)
                    .HasMaxLength(100)
                    .HasColumnName("product_id");

                entity.Property(e => e.RtrLoss)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("rtr_loss");

                entity.Property(e => e.RtrLot)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("rtr_lot");

                entity.Property(e => e.SampleDep)
                    .HasMaxLength(100)
                    .HasColumnName("sample_dep");

                entity.Property(e => e.SampleOrder).HasColumnName("sample_order");

                entity.Property(e => e.TrackinTime)
                    .HasColumnType("datetime")
                    .HasColumnName("trackin_time");

                entity.Property(e => e.TrackinUserId)
                    .HasMaxLength(20)
                    .HasColumnName("trackin_user_id");

                entity.Property(e => e.TrackoutTime)
                    .HasColumnType("datetime")
                    .HasColumnName("trackout_time");

                entity.Property(e => e.TrackoutUserId)
                    .HasMaxLength(20)
                    .HasColumnName("trackout_user_id");

                entity.Property(e => e.Txid).HasColumnName("txid");

                entity.Property(e => e.WaitTrackout).HasDefaultValueSql("((0))");

                entity.Property(e => e.YpNextResource)
                    .HasMaxLength(200)
                    .HasColumnName("yp_next_resource");

                entity.Property(e => e.YpShortlot)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("yp_shortlot");

                entity.HasOne(d => d.Cust)
                    .WithMany(p => p.TbUvWorkorder)
                    .HasForeignKey(d => d.CustId)
                    .HasConstraintName("tb_workorder_FK_custid");

                entity.HasOne(d => d.Product)
                    .WithMany(p => p.TbUvWorkorder)
                    .HasForeignKey(d => d.ProductId)
                    .HasConstraintName("tb_workorder_FK_toolinfo");

                entity.HasOne(d => d.TrackinUser)
                    .WithMany(p => p.TbUvWorkorderTrackinUser)
                    .HasForeignKey(d => d.TrackinUserId)
                    .HasConstraintName("tb_workorder_FK_trackinuserid");

                entity.HasOne(d => d.TrackoutUser)
                    .WithMany(p => p.TbUvWorkorderTrackoutUser)
                    .HasForeignKey(d => d.TrackoutUserId)
                    .HasConstraintName("tb_workorder_FK_trackoutuserid");
            });

            modelBuilder.Entity<ViewUvWorkorder>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("view_uv_workorder");

                entity.Property(e => e.ArrayBlk).HasColumnName("array_blk");

                entity.Property(e => e.CreateDate)
                    .HasMaxLength(20)
                    .HasColumnName("create_date");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("create_time");

                entity.Property(e => e.CustComment)
                    .HasColumnType("ntext")
                    .HasColumnName("cust_comment");

                entity.Property(e => e.CustModelname)
                    .HasMaxLength(200)
                    .HasColumnName("cust_modelname");

                entity.Property(e => e.CustName)
                    .HasMaxLength(30)
                    .HasColumnName("cust_name");

                entity.Property(e => e.CustRevision)
                    .HasMaxLength(20)
                    .HasColumnName("cust_revision");

                entity.Property(e => e.CustToolno)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("cust_toolno");

                entity.Property(e => e.Depth)
                    .HasColumnType("decimal(7, 3)")
                    .HasColumnName("depth");

                entity.Property(e => e.EndCustomer)
                    .HasMaxLength(100)
                    .HasColumnName("end_customer");

                entity.Property(e => e.FormatBg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Format_bg");

                entity.Property(e => e.FormatBold).HasColumnName("Format_bold");

                entity.Property(e => e.FormatFg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Format_fg");

                entity.Property(e => e.HoleCount)
                    .HasMaxLength(50)
                    .HasColumnName("hole_count");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.InsulType)
                    .HasMaxLength(30)
                    .HasColumnName("insul_type");

                entity.Property(e => e.IsDone).HasColumnName("isDone");

                entity.Property(e => e.IsPrinted).HasColumnName("isPrinted");

                entity.Property(e => e.Layer).HasColumnName("layer");

                entity.Property(e => e.LotHistory).HasColumnType("ntext");

                entity.Property(e => e.LotNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("lot_notes");

                entity.Property(e => e.LotType)
                    .HasMaxLength(20)
                    .HasColumnName("lot_type");

                entity.Property(e => e.Lotid)
                    .HasMaxLength(100)
                    .HasColumnName("lotid");

                entity.Property(e => e.MachineCs)
                    .HasMaxLength(300)
                    .HasColumnName("machine_cs");

                entity.Property(e => e.MachineSs)
                    .HasMaxLength(300)
                    .HasColumnName("machine_ss");

                entity.Property(e => e.MainHoleSize)
                    .HasMaxLength(10)
                    .HasColumnName("main_hole_size");

                entity.Property(e => e.MesPrcCode)
                    .HasMaxLength(100)
                    .HasColumnName("mes_prc_code");

                entity.Property(e => e.MesPrcName)
                    .HasMaxLength(200)
                    .HasColumnName("mes_prc_name");

                entity.Property(e => e.MesSeqCode)
                    .HasMaxLength(10)
                    .HasColumnName("mes_seq_code");

                entity.Property(e => e.NftOrderserial)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("nft_orderserial");

                entity.Property(e => e.Pcs).HasColumnName("pcs");

                entity.Property(e => e.Pnlqty).HasColumnName("pnlqty");

                entity.Property(e => e.PrcCode)
                    .HasMaxLength(20)
                    .HasColumnName("prc_code");

                entity.Property(e => e.PrcLayer1)
                    .IsRequired()
                    .HasMaxLength(21)
                    .HasColumnName("prc_layer1");

                entity.Property(e => e.PrcLayer2)
                    .IsRequired()
                    .HasMaxLength(21)
                    .HasColumnName("prc_layer2");

                entity.Property(e => e.PrcName)
                    .HasMaxLength(20)
                    .HasColumnName("prc_name");

                entity.Property(e => e.ProductId)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("product_id");

                entity.Property(e => e.ProductType)
                    .HasMaxLength(20)
                    .HasColumnName("product_type");

                entity.Property(e => e.RtrLoss)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("rtr_loss");

                entity.Property(e => e.Sample).HasColumnName("sample");

                entity.Property(e => e.SampleDep)
                    .HasMaxLength(100)
                    .HasColumnName("sample_dep");

                entity.Property(e => e.SampleOrder).HasColumnName("sample_order");

                entity.Property(e => e.ToolNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("tool_notes");

                entity.Property(e => e.TrackinTime)
                    .HasColumnType("datetime")
                    .HasColumnName("trackin_time");

                entity.Property(e => e.TrackinUsername)
                    .HasMaxLength(20)
                    .HasColumnName("trackin_username");

                entity.Property(e => e.TrackoutTime)
                    .HasColumnType("datetime")
                    .HasColumnName("trackout_time");

                entity.Property(e => e.TrackoutUsername)
                    .HasMaxLength(20)
                    .HasColumnName("trackout_username");

                entity.Property(e => e.Txid).HasColumnName("txid");

                entity.Property(e => e.WorksizeX)
                    .HasColumnType("decimal(6, 2)")
                    .HasColumnName("worksize_x");

                entity.Property(e => e.WorksizeY)
                    .HasColumnType("decimal(6, 2)")
                    .HasColumnName("worksize_y");

                entity.Property(e => e.YpNextResource)
                    .HasMaxLength(200)
                    .HasColumnName("yp_next_resource");

                entity.Property(e => e.YpNextResourceDefault)
                    .HasMaxLength(200)
                    .HasColumnName("yp_next_resource_default");

                entity.Property(e => e.YpNextResourcelist)
                    .HasColumnType("ntext")
                    .HasColumnName("yp_next_resourcelist");

                entity.Property(e => e.YpShortlot)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("yp_shortlot");

                entity.Property(e => e.YpeDatarev)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("ype_datarev");
            });

            modelBuilder.Entity<ViewUvWorkorder2>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("view_uv_workorder2");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("create_time");

                entity.Property(e => e.CustComment)
                    .HasColumnType("ntext")
                    .HasColumnName("cust_comment");

                entity.Property(e => e.CustModelname)
                    .HasMaxLength(200)
                    .HasColumnName("cust_modelname");

                entity.Property(e => e.CustName)
                    .HasMaxLength(30)
                    .HasColumnName("cust_name");

                entity.Property(e => e.CustRevision)
                    .HasMaxLength(10)
                    .HasColumnName("cust_revision")
                    .IsFixedLength();

                entity.Property(e => e.CustToolno)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("cust_toolno");

                entity.Property(e => e.Depth)
                    .HasColumnType("decimal(7, 3)")
                    .HasColumnName("depth");

                entity.Property(e => e.EndCustomer)
                    .HasMaxLength(100)
                    .HasColumnName("end_customer");

                entity.Property(e => e.FormatBg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Format_bg");

                entity.Property(e => e.FormatBold).HasColumnName("Format_bold");

                entity.Property(e => e.FormatFg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Format_fg");

                entity.Property(e => e.HoleCount)
                    .HasMaxLength(50)
                    .HasColumnName("hole_count");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.InsulType)
                    .HasMaxLength(30)
                    .HasColumnName("insul_type");

                entity.Property(e => e.IsDone).HasColumnName("isDone");

                entity.Property(e => e.Layer).HasColumnName("layer");

                entity.Property(e => e.LotNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("lot_notes");

                entity.Property(e => e.LotType)
                    .HasMaxLength(20)
                    .HasColumnName("lot_type");

                entity.Property(e => e.Lotid)
                    .HasMaxLength(100)
                    .HasColumnName("lotid");

                entity.Property(e => e.MachineCs)
                    .HasMaxLength(300)
                    .HasColumnName("machine_cs");

                entity.Property(e => e.MachineSs)
                    .HasMaxLength(300)
                    .HasColumnName("machine_ss");

                entity.Property(e => e.MainHoleSize)
                    .HasMaxLength(10)
                    .HasColumnName("main_hole_size");

                entity.Property(e => e.MesPrcCode)
                    .HasMaxLength(10)
                    .HasColumnName("mes_prc_code");

                entity.Property(e => e.MesPrcName)
                    .HasMaxLength(30)
                    .HasColumnName("mes_prc_name");

                entity.Property(e => e.Pcs).HasColumnName("pcs");

                entity.Property(e => e.Pnlqty).HasColumnName("pnlqty");

                entity.Property(e => e.PrcCode)
                    .HasMaxLength(20)
                    .HasColumnName("prc_code");

                entity.Property(e => e.PrcLayer1)
                    .IsRequired()
                    .HasMaxLength(9)
                    .HasColumnName("prc_layer1");

                entity.Property(e => e.PrcLayer2)
                    .IsRequired()
                    .HasMaxLength(9)
                    .HasColumnName("prc_layer2");

                entity.Property(e => e.PrcName)
                    .HasMaxLength(20)
                    .HasColumnName("prc_name");

                entity.Property(e => e.ProductId)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("product_id");

                entity.Property(e => e.ProductType)
                    .HasMaxLength(20)
                    .HasColumnName("product_type");

                entity.Property(e => e.SampleOrder).HasColumnName("sample_order");

                entity.Property(e => e.ToolNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("tool_notes");

                entity.Property(e => e.TrackinTime)
                    .HasColumnType("datetime")
                    .HasColumnName("trackin_time");

                entity.Property(e => e.TrackinUsername)
                    .HasMaxLength(20)
                    .HasColumnName("trackin_username");

                entity.Property(e => e.TrackoutTime)
                    .HasColumnType("datetime")
                    .HasColumnName("trackout_time");

                entity.Property(e => e.TrackoutUsername)
                    .HasMaxLength(20)
                    .HasColumnName("trackout_username");

                entity.Property(e => e.Txid).HasColumnName("txid");
            });

            modelBuilder.Entity<ViewUvWorkorderDone>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("view_uv_workorder_done");

                entity.Property(e => e.ArrayBlk).HasColumnName("array_blk");

                entity.Property(e => e.CreateDate)
                    .HasMaxLength(20)
                    .HasColumnName("create_date");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("create_time");

                entity.Property(e => e.CustComment)
                    .HasColumnType("ntext")
                    .HasColumnName("cust_comment");

                entity.Property(e => e.CustModelname)
                    .HasMaxLength(200)
                    .HasColumnName("cust_modelname");

                entity.Property(e => e.CustName)
                    .HasMaxLength(30)
                    .HasColumnName("cust_name");

                entity.Property(e => e.CustRevision)
                    .HasMaxLength(10)
                    .HasColumnName("cust_revision")
                    .IsFixedLength();

                entity.Property(e => e.CustToolno)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("cust_toolno");

                entity.Property(e => e.Depth)
                    .HasColumnType("decimal(7, 3)")
                    .HasColumnName("depth");

                entity.Property(e => e.EndCustomer)
                    .HasMaxLength(100)
                    .HasColumnName("end_customer");

                entity.Property(e => e.FormatBg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Format_bg");

                entity.Property(e => e.FormatBold).HasColumnName("Format_bold");

                entity.Property(e => e.FormatFg)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Format_fg");

                entity.Property(e => e.HoleCount)
                    .HasMaxLength(50)
                    .HasColumnName("hole_count");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.InsulType)
                    .HasMaxLength(30)
                    .HasColumnName("insul_type");

                entity.Property(e => e.IsDone).HasColumnName("isDone");

                entity.Property(e => e.IsPrinted).HasColumnName("isPrinted");

                entity.Property(e => e.Layer).HasColumnName("layer");

                entity.Property(e => e.LotHistory).HasColumnType("ntext");

                entity.Property(e => e.LotNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("lot_notes");

                entity.Property(e => e.LotType)
                    .HasMaxLength(20)
                    .HasColumnName("lot_type");

                entity.Property(e => e.Lotid)
                    .HasMaxLength(100)
                    .HasColumnName("lotid");

                entity.Property(e => e.MachineCs)
                    .HasMaxLength(300)
                    .HasColumnName("machine_cs");

                entity.Property(e => e.MachineSs)
                    .HasMaxLength(300)
                    .HasColumnName("machine_ss");

                entity.Property(e => e.MainHoleSize)
                    .HasMaxLength(10)
                    .HasColumnName("main_hole_size");

                entity.Property(e => e.MesPrcCode)
                    .HasMaxLength(100)
                    .HasColumnName("mes_prc_code");

                entity.Property(e => e.MesPrcName)
                    .HasMaxLength(200)
                    .HasColumnName("mes_prc_name");

                entity.Property(e => e.MesSeqCode)
                    .HasMaxLength(10)
                    .HasColumnName("mes_seq_code");

                entity.Property(e => e.NftOrderserial)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("nft_orderserial");

                entity.Property(e => e.Pcs).HasColumnName("pcs");

                entity.Property(e => e.Pnlqty).HasColumnName("pnlqty");

                entity.Property(e => e.PrcCode)
                    .HasMaxLength(20)
                    .HasColumnName("prc_code");

                entity.Property(e => e.PrcLayer1)
                    .IsRequired()
                    .HasMaxLength(21)
                    .HasColumnName("prc_layer1");

                entity.Property(e => e.PrcLayer2)
                    .IsRequired()
                    .HasMaxLength(21)
                    .HasColumnName("prc_layer2");

                entity.Property(e => e.PrcName)
                    .HasMaxLength(20)
                    .HasColumnName("prc_name");

                entity.Property(e => e.ProductId)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("product_id");

                entity.Property(e => e.ProductType)
                    .HasMaxLength(20)
                    .HasColumnName("product_type");

                entity.Property(e => e.RtrLoss)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("rtr_loss");

                entity.Property(e => e.Sample).HasColumnName("sample");

                entity.Property(e => e.SampleDep)
                    .HasMaxLength(100)
                    .HasColumnName("sample_dep");

                entity.Property(e => e.SampleOrder).HasColumnName("sample_order");

                entity.Property(e => e.ToolNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("tool_notes");

                entity.Property(e => e.TrackinTime)
                    .HasColumnType("datetime")
                    .HasColumnName("trackin_time");

                entity.Property(e => e.TrackinUsername)
                    .HasMaxLength(20)
                    .HasColumnName("trackin_username");

                entity.Property(e => e.TrackoutTime)
                    .HasColumnType("datetime")
                    .HasColumnName("trackout_time");

                entity.Property(e => e.TrackoutUsername)
                    .HasMaxLength(20)
                    .HasColumnName("trackout_username");

                entity.Property(e => e.Txid).HasColumnName("txid");

                entity.Property(e => e.WorksizeX)
                    .HasColumnType("decimal(6, 2)")
                    .HasColumnName("worksize_x");

                entity.Property(e => e.WorksizeY)
                    .HasColumnType("decimal(6, 2)")
                    .HasColumnName("worksize_y");

                entity.Property(e => e.YpNextResource)
                    .HasMaxLength(200)
                    .HasColumnName("yp_next_resource");

                entity.Property(e => e.YpShortlot)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("yp_shortlot");

                entity.Property(e => e.YpeDatarev)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("ype_datarev");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}