// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace DAWON_UV_INVENTORY_PROTO.Models
{
    [DbContext(typeof(Db_Uv_InventoryContext))]
    public partial class Db_Uv_InventoryContextModel : RuntimeModel
    {
        static Db_Uv_InventoryContextModel()
        {
            var model = new Db_Uv_InventoryContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static Db_Uv_InventoryContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
