// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAWON_UV_INVENTORY_PROTO.Models
{
    public partial class TbBomYpeMaterial
    {
        public string Bomid { get; set; }
        public string RootBomid { get; set; }
        public string Botassemblyitemname { get; set; }
        public string RootAssemblyitemid { get; set; }
        public string RootAssemblyitemversion { get; set; }
        public string Spec { get; set; }
        public short? Lvl { get; set; }
        public string Userlayer { get; set; }
        public string Maker { get; set; }
        public string Assemblyitembomid { get; set; }
        public string Assemblyitemid { get; set; }
        public string Assemblyitemversion { get; set; }
        public double? Arraypcs { get; set; }
        public string Pnlsize { get; set; }
        public double? Pnlsizexaxis { get; set; }
        public double? Pnlsizeyaxis { get; set; }
        public string Consumabletype2 { get; set; }
        public string Color { get; set; }
        public double? Assemblyqty { get; set; }
        public string Usersequence { get; set; }
        public double? Requirementqty { get; set; }
        public string Parentbomid { get; set; }
        public string ParentsAssemblyitemid { get; set; }
        public string ParentsAssemblyitemversion { get; set; }
        public string Workmethod { get; set; }
        public decimal? Calculatepcs { get; set; }
        public string Consumabletype { get; set; }
        public string Worksurface { get; set; }
        public string Inktype { get; set; }
        public string Plantid { get; set; }
    }
}