// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAWON_UV_INVENTORY_PROTO.Models
{
    public partial class TbCustomer
    {
        public TbCustomer()
        {
            TbUvToolinfo = new HashSet<TbUvToolinfo>();
            TbUvWorkorder = new HashSet<TbUvWorkorder>();
        }

        public string CustId { get; set; }
        public string CustName { get; set; }
        public string CustCode { get; set; }

        public virtual ICollection<TbUvToolinfo> TbUvToolinfo { get; set; }
        public virtual ICollection<TbUvWorkorder> TbUvWorkorder { get; set; }
    }
}