// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAWON_UV_INVENTORY_PROTO.Models
{
    public partial class TbMachine
    {
        public string MachineId { get; set; }
        public string MachineName { get; set; }
        public string Department { get; set; }
        public string MachineModelname { get; set; }
        public string MachineMaker { get; set; }
        public string MachineShortname { get; set; }
    }
}