// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAWON_UV_INVENTORY_PROTO.Models
{
    public partial class TbUsers
    {
        public TbUsers()
        {
            TbUvWorkorderTrackinUser = new HashSet<TbUvWorkorder>();
            TbUvWorkorderTrackoutUser = new HashSet<TbUvWorkorder>();
        }

        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserGroup { get; set; }
        public string UserRole { get; set; }
        public bool? IsRetired { get; set; }

        public virtual ICollection<TbUvWorkorder> TbUvWorkorderTrackinUser { get; set; }
        public virtual ICollection<TbUvWorkorder> TbUvWorkorderTrackoutUser { get; set; }
    }
}