// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAWON_UV_INVENTORY_PROTO.Models
{
    public partial class ViewUvWorkorderDone
    {
        public string EndCustomer { get; set; }
        public string Lotid { get; set; }
        public string CustModelname { get; set; }
        public string CustRevision { get; set; }
        public string CustToolno { get; set; }
        public string MesPrcName { get; set; }
        public string PrcName { get; set; }
        public decimal? WorksizeX { get; set; }
        public decimal? WorksizeY { get; set; }
        public DateTime? CreateTime { get; set; }
        public decimal? Depth { get; set; }
        public short? Pnlqty { get; set; }
        public Guid Txid { get; set; }
        public string TrackinUsername { get; set; }
        public DateTime? TrackinTime { get; set; }
        public string TrackoutUsername { get; set; }
        public DateTime? TrackoutTime { get; set; }
        public string LotType { get; set; }
        public string LotNotes { get; set; }
        public string HoleCount { get; set; }
        public string MachineCs { get; set; }
        public string MachineSs { get; set; }
        public bool? Sample { get; set; }
        public string ProductId { get; set; }
        public int? ArrayBlk { get; set; }
        public int? Pcs { get; set; }
        public int? Layer { get; set; }
        public DateTime? CreateDate { get; set; }
        public string PrcLayer1 { get; set; }
        public string PrcLayer2 { get; set; }
        public string MesPrcCode { get; set; }
        public string ProductType { get; set; }
        public string ToolNotes { get; set; }
        public string CustComment { get; set; }
        public string InsulType { get; set; }
        public string MainHoleSize { get; set; }
        public string MesSeqCode { get; set; }
        public string PrcCode { get; set; }
        public bool? IsDone { get; set; }
        public bool? IsPrinted { get; set; }
        public long Id { get; set; }
        public string CustName { get; set; }
        public bool? SampleOrder { get; set; }
    }
}