namespace ConnectorYPE.Models
{
    public class YPSpecInfoModel
    {
        public string? mincl { get; set; }
        public string? deliverydate { get; set; }
        public string? arysizeyaxis { get; set; }
        public string? productdimensions { get; set; }
        public string? invaliddate { get; set; }
        public string? uom { get; set; }
        public string? hazardoussubstances { get; set; }
        public string? pnlmm { get; set; }
        public string? inputscale2 { get; set; }
        public string? customermodelname { get; set; }
        public string? inputscale1 { get; set; }
        public string? inputapn { get; set; }
        public string? impedancespec21 { get; set; }
        public string? impedancespec22 { get; set; }
        public string? impedancespec23 { get; set; }
        public string? qrbusinessinfo { get; set; }
        public string? impedanceapplylayer2 { get; set; }
        public string? impedanceapplylayer1 { get; set; }
        public string? projectname { get; set; }
        public string? impedanceapplylayer3 { get; set; }
        public string? itemname { get; set; }
        public string? separatingportion { get; set; }
        public string? fileext { get; set; }
        public string? jobtype { get; set; }
        public string? ulmark { get; set; }
        public string? flatness12 { get; set; }
        public string? pnlsizeyaxis { get; set; }
        public string? flatness11 { get; set; }
        public string? filename { get; set; }
        public string? assy { get; set; }
        public string? saleordercategory { get; set; }
        public string? contractor { get; set; }
        public string? qrbusinesssub { get; set; }
        public string? productrating { get; set; }
        public string? reliability { get; set; }
        public string? registrationdate { get; set; }
        public string? filesize { get; set; }
        public string? layer { get; set; }
        public string? measurement { get; set; }
        public string? pcsary { get; set; }
        public string? isweekmng { get; set; }
        public string? salestype { get; set; }
        public string? estimateyield { get; set; }
        public string? qrmaterialrev { get; set; }
        public string? specperson { get; set; }
        public string? enduser { get; set; }
        public string? customerrev { get; set; }
        public string? arraydiagonallength { get; set; }
        public string? rtrsht { get; set; }
        public string? pcssizeyaxis { get; set; }
        public string? itemaccount { get; set; }
        public string? oxide { get; set; }
        public string? salesowner { get; set; }
        public string? camownername { get; set; }
        public string? x { get; set; }
        public string? y { get; set; }
        public string? arysizexaxis { get; set; }
        public string? flatnesstwo11 { get; set; }
        public string? flatnesstwo12 { get; set; }
        public string? customeritemversion { get; set; }
        public string? inputnumaxis2 { get; set; }
        public string? pcspnl { get; set; }
        public string? impedance { get; set; }
        public string? inputnumaxis1 { get; set; }
        public string? lotcontrol { get; set; }
        public string? itemversion { get; set; }
        public string? elongation { get; set; }
        public string? userlayer { get; set; }
        public string? producttype { get; set; }
        public string? impedancetype21 { get; set; }
        public string? copperfoildownlayer { get; set; }
        public string? inputsizexaxis { get; set; }
        public string? impedancetype23 { get; set; }
        public string? impedancetype22 { get; set; }
        public string? productiontype { get; set; }
        public string? shipto { get; set; }
        public string? fileid { get; set; }
        public string? specpersonname { get; set; }
        public string? outboundformat { get; set; }
        public string? psrtolerance { get; set; }
        public string? flatnesstwo21 { get; set; }
        public string? flatnesstwo22 { get; set; }
        public string? basiccode { get; set; }
        public string? pnlsizexaxis { get; set; }
        public string? salesownername { get; set; }
        public string? mainfactory { get; set; }
        public string? pcssizexaxis { get; set; }
        public string? minpsr { get; set; }
        public string? inputtype { get; set; }
        public string? remark { get; set; }
        public string? flatness21 { get; set; }
        public string? itemclass { get; set; }
        public string? itemid { get; set; }
        public string? flatness22 { get; set; }
        public string? qrproductiontype { get; set; }
        public string? endtype { get; set; }
        public string? pcsmm { get; set; }
        public string? customername { get; set; }
        public string? billtoname { get; set; }
        public string? customeritemid { get; set; }
        public string? camowner { get; set; }
        public string? shiptoname { get; set; }
        public string? receivenewdata { get; set; }
        public string? xout { get; set; }
        public string? copperfoiluplayer { get; set; }
        public string? billto { get; set; }
        public string? contractorname { get; set; }
        public string? customer { get; set; }
    }
}
